// Generated by `npm run build:extension` (backend/). Edit extension/src/content.ts instead.
(() => {
  // src/inpage.ts
  var CAPTURE_LIMITS = {
    maxSections: 40,
    maxSectionHtmlChars: 1e5,
    maxCopiedElements: 2e4,
    // per section
    maxStyledElements: 1500,
    // per section; styles are the expensive part
    maxFontCssChars: 5e4,
    maxScreenshotHeight: 8e3
  };
  function desktopPass({ maxSections, maxCopiedElements, maxStyledElements, maxFontCssChars }) {
    const w = window;
    const isBlock = (el) => {
      const rect = el.getBoundingClientRect();
      if (rect.height < 100 || rect.width < 100) return false;
      return !!el.textContent?.trim() || el.querySelector("img") !== null;
    };
    const candidateSet = /* @__PURE__ */ new Set();
    document.querySelectorAll(
      'section, header, footer, main, nav, body > div, main > div, div[class*="section"], div[id*="section"]'
    ).forEach((el) => candidateSet.add(el));
    const valid = [...candidateSet].filter(isBlock);
    const coverage = (el, parts) => {
      const box = el.getBoundingClientRect();
      if (box.height <= 0) return 0;
      const spans = parts.map((part) => part.getBoundingClientRect()).map((r) => [Math.max(r.top, box.top), Math.min(r.bottom, box.bottom)]).filter(([top, bottom]) => bottom > top).sort((a, b) => a[0] - b[0]);
      let covered = 0;
      let end = -Infinity;
      for (const [top, bottom] of spans) {
        if (bottom <= end) continue;
        covered += bottom - Math.max(top, end);
        end = bottom;
      }
      return covered / box.height;
    };
    const mixedContainers = /* @__PURE__ */ new Set();
    const nonWrappers = valid.filter((el) => {
      const inside = valid.filter((other) => other !== el && el.contains(other));
      if (inside.length < 2) return true;
      if (coverage(el, inside) >= 0.7) return false;
      mixedContainers.add(el);
      return true;
    });
    const kept = nonWrappers.filter(
      (el) => !nonWrappers.some((other) => other !== el && other.contains(el))
    );
    const neverSplit = ["HEADER", "FOOTER", "NAV"];
    const maxHeight = window.innerHeight * 2;
    const chosen = [];
    const queue = [...kept];
    while (queue.length) {
      const el = queue.shift();
      const limit = el.tagName === "SECTION" ? maxHeight * 1.5 : maxHeight;
      const oversized = el.getBoundingClientRect().height > limit;
      if (neverSplit.includes(el.tagName) || !(oversized || mixedContainers.has(el))) {
        chosen.push(el);
        continue;
      }
      let branch = el;
      let kids = [...el.children].filter(isBlock);
      while (kids.length === 1) {
        branch = kids[0];
        kids = [...branch.children].filter(isBlock);
      }
      const byTop = kids.map((kid) => ({ kid, r: kid.getBoundingClientRect() })).sort((a, b) => a.r.top - b.r.top);
      const stacked = byTop.every(
        ({ r }, i) => i === 0 || r.top >= byTop[i - 1].r.bottom - 4
        // no vertical overlap
      );
      if (kids.length >= 2 && stacked) queue.unshift(...byTop.map(({ kid }) => kid));
      else chosen.push(el);
    }
    const textLength = (el) => (el.innerText || "").trim().length;
    const overlapArea = (a, b) => Math.max(0, Math.min(a.right, b.right) - Math.max(a.left, b.left)) * Math.max(0, Math.min(a.bottom, b.bottom) - Math.max(a.top, b.top));
    const dropLayers = (list) => {
      const visible = list.filter((el) => !el.closest('[aria-hidden="true"]'));
      return visible.filter((el) => {
        const a = el.getBoundingClientRect();
        return !visible.some((other) => {
          if (other === el) return false;
          const b = other.getBoundingClientRect();
          const smaller = Math.min(a.width * a.height, b.width * b.height);
          if (smaller === 0 || overlapArea(a, b) / smaller < 0.8) return false;
          const diff = textLength(other) - textLength(el);
          return diff > 0 || diff === 0 && !!(other.compareDocumentPosition(el) & Node.DOCUMENT_POSITION_FOLLOWING);
        });
      });
    };
    const deduped = dropLayers(chosen);
    const areaCoverage = (el, parts) => {
      const box = el.getBoundingClientRect();
      const area = box.width * box.height;
      if (area <= 0) return 0;
      const covered = parts.reduce((sum, part) => sum + overlapArea(box, part.getBoundingClientRect()), 0);
      return Math.min(1, covered / area);
    };
    const final = new Set(deduped);
    const recover = (el) => {
      if (final.has(el) || el.closest('[aria-hidden="true"]')) return;
      const inner = [...final].filter((section) => el.contains(section));
      const height = el.getBoundingClientRect().height;
      if (!inner.length) {
        if (isBlock(el) && height >= 120) final.add(el);
        return;
      }
      const box = el.getBoundingClientRect();
      const fullyInside = inner.every((section) => {
        const r = section.getBoundingClientRect();
        return overlapArea(box, r) >= 0.95 * r.width * r.height;
      });
      const mergeable = inner.length <= 2 && fullyInside && areaCoverage(el, inner) < 0.5;
      if (el !== document.body && isBlock(el) && height <= maxHeight && mergeable) {
        inner.forEach((section) => final.delete(section));
        final.add(el);
        return;
      }
      [...el.children].forEach(recover);
    };
    recover(document.body);
    chosen.length = 0;
    chosen.push(...dropLayers([...final]));
    chosen.sort(
      (a, b) => a.compareDocumentPosition(b) & Node.DOCUMENT_POSITION_FOLLOWING ? -1 : 1
    );
    chosen.splice(maxSections);
    const inheritedProps = [
      "color",
      "font-family",
      "font-size",
      "font-weight",
      "line-height",
      "letter-spacing",
      "text-align",
      "text-transform"
    ];
    const defaultValues = {
      "position": ["static"],
      "flex-direction": ["row"],
      "flex-wrap": ["nowrap"],
      "justify-content": ["normal", "flex-start", "start"],
      "align-items": ["normal", "stretch"],
      "gap": ["normal", "0px"],
      "grid-template-columns": ["none"],
      "background-color": ["rgba(0, 0, 0, 0)", "transparent"],
      "background-image": ["none"],
      "padding": ["0px"],
      "border-radius": ["0px"],
      "box-shadow": ["none"],
      "max-width": ["none"],
      "opacity": ["1"]
    };
    const sides = ["top", "right", "bottom", "left"];
    const computeDecls = (el, parent) => {
      const cs = getComputedStyle(el);
      const parentCs = parent ? getComputedStyle(parent) : null;
      const decls = /* @__PURE__ */ new Map();
      const display = cs.getPropertyValue("display");
      if (display === "none" || display.includes("flex") || display.includes("grid")) {
        decls.set("display", display);
      }
      inheritedProps.forEach((prop) => {
        const value = cs.getPropertyValue(prop);
        if (value && (!parentCs || parentCs.getPropertyValue(prop) !== value)) {
          decls.set(prop, value);
        }
      });
      Object.entries(defaultValues).forEach(([prop, defaults]) => {
        const value = cs.getPropertyValue(prop);
        if (value && !defaults.includes(value)) decls.set(prop, value);
      });
      const borders = sides.map(
        (side) => cs.getPropertyValue(`border-${side}-width`) !== "0px" && cs.getPropertyValue(`border-${side}-style`) !== "none" ? cs.getPropertyValue(`border-${side}`) : ""
      );
      if (borders.every((b) => b && b === borders[0])) {
        decls.set("border", borders[0]);
      } else {
        sides.forEach((side, s) => {
          if (borders[s]) decls.set(`border-${side}`, borders[s]);
        });
      }
      return decls;
    };
    const toStyle = (decls) => [...decls].map(([prop, value]) => `${prop}:${value}`).join(";");
    const describePseudo = (el, which) => {
      const cs = getComputedStyle(el, which);
      const content = cs.getPropertyValue("content");
      if (!content || content === "none" || content === "normal") return "";
      const parts = [`content:${content}`];
      const hasText = /^["'].+["']$/.test(content);
      [
        "background-color",
        "background-image",
        "width",
        "height",
        "position",
        "top",
        "left",
        "right",
        "bottom",
        "border-radius",
        ...hasText ? ["color", "font-size"] : []
      ].forEach((prop) => {
        const value = cs.getPropertyValue(prop);
        if (value && !["auto", "none", "normal", "static", "0px", "rgba(0, 0, 0, 0)"].includes(value)) {
          parts.push(`${prop}:${value}`);
        }
      });
      return parts.join(";");
    };
    const outDoc = document.implementation.createHTMLDocument("");
    const skipTags = /* @__PURE__ */ new Set([
      "SCRIPT",
      "STYLE",
      "NOSCRIPT",
      "IFRAME",
      "TEMPLATE",
      "LINK",
      "META",
      "SOURCE",
      "TRACK"
    ]);
    const tagged = [];
    const roots = [];
    const usedIds = /* @__PURE__ */ new Set();
    const sections = chosen.map((el, index) => {
      let copied = 0;
      let styled = 0;
      const appendChild = (target, node, parent) => {
        if (node.nodeType === Node.TEXT_NODE) {
          target.appendChild(outDoc.createTextNode(node.textContent || ""));
        } else if (node.nodeType === Node.ELEMENT_NODE) {
          const copy = build(node, parent);
          if (copy) target.appendChild(copy);
        }
      };
      const build = (orig, parent) => {
        if (skipTags.has(orig.tagName.toUpperCase()) || copied >= maxCopiedElements) return null;
        copied++;
        if (orig instanceof HTMLSlotElement) {
          const fragment = outDoc.createDocumentFragment();
          const assigned = orig.assignedNodes({ flatten: true });
          (assigned.length ? assigned : [...orig.childNodes]).forEach(
            (n) => appendChild(fragment, n, parent)
          );
          return fragment;
        }
        const copy = outDoc.importNode(orig, false);
        if (orig instanceof HTMLImageElement) {
          let src = orig.currentSrc || orig.src;
          if (!src || src.startsWith("data:")) {
            const picture = orig.parentElement instanceof HTMLPictureElement ? orig.parentElement : null;
            const srcset = orig.getAttribute("srcset") || orig.getAttribute("data-srcset") || picture?.querySelector("source[srcset]")?.getAttribute("srcset");
            const largest = srcset?.split(",").map((candidate) => candidate.trim().split(/\s+/)[0]).filter(Boolean).pop();
            const fallback = orig.getAttribute("data-src") || orig.getAttribute("data-lazy-src") || largest;
            if (fallback) {
              try {
                src = new URL(fallback, document.baseURI).href;
              } catch {
              }
            }
          }
          if (src.startsWith("data:") && src.length > 500) src = "";
          copy.setAttribute("src", src);
          copy.removeAttribute("srcset");
          copy.removeAttribute("sizes");
        } else if (orig instanceof HTMLVideoElement) {
          if (orig.currentSrc) copy.setAttribute("src", orig.currentSrc);
          if (orig.getAttribute("poster")) copy.setAttribute("poster", orig.poster);
        } else if (orig instanceof HTMLAnchorElement && orig.getAttribute("href")) {
          copy.setAttribute("href", orig.href);
        }
        [...copy.attributes].forEach((attr) => {
          if (attr.name.startsWith("data-") || attr.name.startsWith("on")) {
            copy.removeAttribute(attr.name);
          }
        });
        const isSvgChild = orig instanceof SVGElement && !(orig instanceof SVGSVGElement);
        if (!isSvgChild && styled < maxStyledElements) {
          styled++;
          const decls = computeDecls(orig, parent);
          if (decls.size) copy.setAttribute("style", toStyle(decls));
          else copy.removeAttribute("style");
          tagged.push({ orig, copy, parent, desktop: decls });
          const before = describePseudo(orig, "::before");
          const after = describePseudo(orig, "::after");
          if (before) copy.setAttribute("data-before", before);
          if (after) copy.setAttribute("data-after", after);
        }
        if (orig instanceof SVGSVGElement) return copy;
        const children = orig.shadowRoot ? orig.shadowRoot.childNodes : orig.childNodes;
        children.forEach((child) => appendChild(copy, child, orig));
        return copy;
      };
      const root = build(el, null);
      roots.push(root);
      let id = el.id && !usedIds.has(el.id) ? el.id : `section-${index}`;
      while (usedIds.has(id)) id += "_";
      usedIds.add(id);
      const rect = el.getBoundingClientRect();
      return {
        id,
        tagName: el.tagName.toLowerCase(),
        // Visible text only, for the preview card.
        text: (el.innerText || el.textContent || "").replace(/\s+/g, " ").trim().substring(0, 200),
        rect: {
          x: rect.x + window.scrollX,
          y: rect.y + window.scrollY,
          width: rect.width,
          height: rect.height
        }
      };
    });
    w.__scrape = { tagged, roots, computeDecls };
    const families = /* @__PURE__ */ new Set();
    document.fonts.forEach((font) => {
      if (font.status === "loaded") families.add(font.family.replace(/^["']|["']$/g, ""));
    });
    const imports = [];
    const faces = [];
    document.querySelectorAll('link[rel="stylesheet"][href]').forEach((link) => {
      if (/fonts\.googleapis\.com|fonts\.bunny\.net|use\.typekit\.net/.test(link.href)) {
        imports.push(`@import url("${link.href}");`);
      }
    });
    [...document.styleSheets].forEach((sheet) => {
      let rules;
      try {
        rules = sheet.cssRules;
      } catch {
        return;
      }
      const base = sheet.href || document.baseURI;
      [...rules].forEach((rule) => {
        if (!(rule instanceof CSSFontFaceRule)) return;
        const family = rule.style.getPropertyValue("font-family").replace(/^["']|["']$/g, "");
        if (!families.has(family)) return;
        faces.push(
          rule.cssText.replace(/url\((["']?)([^"')]+)\1\)/g, (_m, _q, u) => {
            try {
              return `url("${new URL(u, base).href}")`;
            } catch {
              return `url("${u}")`;
            }
          })
        );
      });
    });
    let css = "";
    for (const rule of [...imports, ...faces]) {
      if (css.length + rule.length + 1 > maxFontCssChars) break;
      css += rule + "\n";
    }
    return {
      sections,
      fonts: {
        families: [...families].filter((f) => f.length <= 100).slice(0, 20),
        css
      },
      pageHeight: document.documentElement.scrollHeight
    };
  }
  function finishPass({ maxSectionHtmlChars, recordMobile }) {
    const { tagged, roots, computeDecls } = window.__scrape;
    if (recordMobile) tagged.forEach(({ orig, copy, parent, desktop }) => {
      if (!orig.isConnected) return;
      const mobile = computeDecls(orig, parent);
      const diff = [];
      mobile.forEach((value, prop) => {
        if (desktop.get(prop) !== value) diff.push(`${prop}:${value}`);
      });
      const cs = getComputedStyle(orig);
      desktop.forEach((_value, prop) => {
        if (!mobile.has(prop)) {
          const value = cs.getPropertyValue(prop);
          if (value) diff.push(`${prop}:${value}`);
        }
      });
      if (diff.length) copy.setAttribute("data-mobile-style", diff.join(";"));
    });
    return roots.map((root) => {
      const html = root.outerHTML;
      if (html.length <= maxSectionHtmlChars) return html;
      return html.slice(0, html.lastIndexOf(">", maxSectionHtmlChars - 1) + 1);
    });
  }
  async function scrollThrough() {
    const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
    let box = null;
    let el = document.elementFromPoint(innerWidth / 2, innerHeight / 2);
    while (el && el !== document.documentElement) {
      const overflowY = getComputedStyle(el).overflowY;
      if ((overflowY === "auto" || overflowY === "scroll") && el.scrollHeight > el.clientHeight + 50) {
        box = el;
        break;
      }
      el = el.parentElement;
    }
    const position = () => window.scrollY + (box?.scrollTop ?? 0);
    const step = Math.round(innerHeight * 0.8);
    let unchanged = 0;
    for (let i = 0; i < 40 && unchanged < 3; i++) {
      const before = position();
      if (box) box.scrollBy(0, step);
      else window.scrollBy(0, step);
      await wait(150);
      unchanged = position() === before ? unchanged + 1 : 0;
    }
    window.scrollTo(0, 0);
    if (box) box.scrollTop = 0;
    await wait(400);
  }

  // ../extension/src/content.ts
  async function prepare() {
    await scrollThrough();
    const desktop = desktopPass({
      maxSections: CAPTURE_LIMITS.maxSections,
      maxCopiedElements: CAPTURE_LIMITS.maxCopiedElements,
      maxStyledElements: CAPTURE_LIMITS.maxStyledElements,
      maxFontCssChars: CAPTURE_LIMITS.maxFontCssChars
    });
    const htmls = finishPass({ maxSectionHtmlChars: CAPTURE_LIMITS.maxSectionHtmlChars, recordMobile: false });
    return {
      url: location.href,
      sections: desktop.sections.map((section, i) => ({ ...section, html: htmls[i] ?? "" })),
      fonts: desktop.fonts,
      pageHeight: desktop.pageHeight,
      viewport: { width: window.innerWidth, height: window.innerHeight },
      maxScreenshotHeight: CAPTURE_LIMITS.maxScreenshotHeight
    };
  }
  function scrollToY(y) {
    window.scrollTo({ top: y, left: 0, behavior: "instant" });
    return new Promise((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve(window.scrollY))));
  }
  var hidden = [];
  function hideFixed() {
    for (const el of Array.from(document.querySelectorAll("body *"))) {
      const position = getComputedStyle(el).position;
      if (position !== "fixed" && position !== "sticky") continue;
      hidden.push({ el, value: el.style.getPropertyValue("visibility"), priority: el.style.getPropertyPriority("visibility") });
      el.style.setProperty("visibility", "hidden", "important");
    }
    return hidden.length;
  }
  function restore(scrollY) {
    for (const { el, value, priority } of hidden) {
      if (value) el.style.setProperty("visibility", value, priority);
      else el.style.removeProperty("visibility");
    }
    hidden = [];
    window.scrollTo({ top: scrollY, left: 0, behavior: "instant" });
  }
  globalThis.__w2c = { prepare, scrollToY, hideFixed, restore, startScrollY: window.scrollY };
})();
